FROM golang:1.23

RUN apt-get update && apt-get install -y ca-certificates tzdata && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash pwuser
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/worker github.com/egor3f/rssalchemy/cmd/worker

CMD ["/app/bin/worker"]
